// @ts-nocheck
namespace $.$$ {

	// Одна и та же кнопка закрытия для всех модалок лендинга (Rsvp_modal, Cfp_modal).
	// marginRight отрицательный, чтобы крестик выходил за padding диалога: замерено 17px
	// от правого края вместо 33px. Ширина кнопки больше суммы padding'ов — $mol_button_minor
	// добавляет свои, поэтому значение подобрано по факту, а не расчётом.
	const close_btn = {
		background: 'transparent',
		border: 'none',
		boxShadow: 'none',
		color: '#aaaaaa',
		fontFamily: 'var(--font-mono)',
		fontSize: '12px',
		padding: '6px 12px',
		marginRight: '-16px',
		cursor: 'pointer',
		transition: 'color 0.2s ease',
		':hover': {
			color: 'var(--color-caution-yellow)',
			background: 'transparent',
			boxShadow: 'none',
		},
	}

	// Общий вид CFP-кнопки: одна в блоке «Программа», вторая в коробке
	// отсчёта, когда митап прошёл. Выравнивание у каждой своё.
	const cfp_btn = {
		textTransform: 'uppercase',
		background: 'rgba(255, 243, 19, 0.08)',
		color: 'var(--color-caution-yellow)',
		fontFamily: 'var(--font-mono)',
		fontWeight: '700',
		fontSize: '13px',
		padding: '8px 16px',
		borderRadius: '6px',
		border: '1px solid rgba(255, 243, 19, 0.35)',
		boxShadow: 'none',
		cursor: 'pointer',
		transition: 'all 0.2s ease',
		':hover': {
			backgroundColor: 'var(--color-caution-yellow)',
			color: '#000000',
			borderColor: 'var(--color-caution-yellow)',
		},
	}

	const skel_base = {
		background: 'linear-gradient(90deg, rgba(255, 255, 255, 0.05) 25%, rgba(255, 255, 255, 0.12) 50%, rgba(255, 255, 255, 0.05) 75%)',
		backgroundSize: '200% 100%',
		animation: 'pjs_skeleton_shimmer 1.8s infinite ease-in-out',
		borderRadius: '4px',
	}

	// Общий вид жёлтой пилюли в карточке события: «На карте» до отзывов и
	// «Оставить отзыв» в течение недели после митапа.
	const pill_link = {
		textTransform: 'uppercase',
		fontFamily: '\'JetBrains Mono\', monospace',
		fontSize: '11px',
		color: '#fff313',
		background: 'rgba(255, 243, 19, 0.08)',
		border: '1px solid rgba(255, 243, 19, 0.4)',
		padding: '4px 12px',
		borderRadius: '6px',
		textDecoration: 'none',
		transition: 'all 0.2s ease',
		display: 'inline-flex',
		alignItems: 'center',
		cursor: 'pointer',
		':hover': {
			background: '#fff313',
			color: '#000000',
			borderColor: '#fff313',
		},
	}

	$mol_style_define( $piterjs_landing, {
		display: 'block',
		width: '100vw',
		minWidth: '100vw',
		maxWidth: '100vw',
		minHeight: '100vh',
		height: '100vh',
		overflowY: 'auto',
		overflowX: 'hidden',
		backgroundColor: '#000000',
		color: '#eeeeee',
		fontFamily: '\'Inter\', \'Space Grotesk\', ui-sans-serif, system-ui, -apple-system, sans-serif',
		position: 'relative',
		boxSizing: 'border-box',
		margin: '0',
		padding: '0',
		border: 'none',
		'--color-caution-yellow': '#fff313',
		'--color-midnight-steel': '#000000',
		'--color-industrial-white': '#eeeeee',
		'--color-carbon': '#333333',
		'--color-gunmetal': '#4b4b4b',
		'--color-aluminum': '#afafaf',
		'--font-mono': '\'JetBrains Mono\', monospace',
		'*': {
			boxSizing: 'border-box',
		},
		Header: {
			position: 'fixed',
			top: '0',
			left: '0',
			width: '100%',
			zIndex: '1000',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			padding: '16px 36px',
			backgroundColor: 'rgba(0, 0, 0, 0.85)',
			backdropFilter: 'blur(12px)',
			borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
			boxSizing: 'border-box',
		},
		Header_inner: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
		},
		Logo_link: {
			display: 'flex',
			alignItems: 'center',
			gap: '10px',
			textDecoration: 'none',
			color: '#ffffff',
			paddingLeft: '0',
			marginLeft: '0',
			paddingTop: '0',
			paddingBottom: '0',
		},
		Logo_img: {
			width: '28px',
			height: '28px',
			borderRadius: '4px',
		},
		Logo_title: {
			fontFamily: 'var(--font-mono)',
			fontWeight: '700',
			fontSize: '16px',
			letterSpacing: '1px',
			color: '#ffffff',
		},
		Logo_tag: {
			fontFamily: 'var(--font-mono)',
			fontSize: '10px',
			padding: '2px 6px',
			backgroundColor: 'var(--color-caution-yellow)',
			color: '#000000',
			fontWeight: '700',
			borderRadius: '4px',
		},
		Nav: {
			display: 'flex',
			alignItems: 'center',
			gap: '8px',
			background: '#1a1a1a',
			padding: '4px 6px',
			borderRadius: '6px',
			border: '1px solid #333333',
			$mol_link: {
				padding: '6px 14px',
				fontSize: '13px',
				fontWeight: '500',
				color: '#afafaf',
				textDecoration: 'none',
				borderRadius: '4px',
				transition: 'all 0.2s ease',
				':hover': {
					color: '#ffffff',
					background: 'rgba(255, 255, 255, 0.08)',
				},
			},
		},
		Nav_actions: {
			display: 'flex',
			alignItems: 'center',
			gap: '12px',
		},
		Back_link: {
			textTransform: 'uppercase',
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: '#afafaf',
			textDecoration: 'none',
			padding: '8px 12px',
			border: '1px solid #333333',
			borderRadius: '6px',
			background: 'transparent',
			transition: 'color 0.15s ease, border-color 0.15s ease, background-color 0.15s ease',
			':hover': {
				color: '#fff313',
				borderColor: '#fff313',
				background: 'rgba(255, 243, 19, 0.08)',
			},
		},
		Rsvp_btn: {
			textTransform: 'uppercase',
			backgroundColor: 'var(--color-caution-yellow)',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontWeight: '700',
			fontSize: '13px',
			padding: '8px 16px',
			borderRadius: '6px',
			border: 'none',
			cursor: 'pointer',
			transition: 'background-color 0.15s ease',
			':hover': {
				backgroundColor: '#ffe600',
			},
		},
		Burger_btn: {
			display: 'none',
			width: '32px',
			height: '32px',
			minHeight: '32px',
			maxHeight: '32px',
			minWidth: '32px',
			maxWidth: '32px',
			padding: '0',
			background: 'transparent',
			backgroundColor: 'transparent',
			border: 'none',
			boxShadow: 'none',
			outline: 'none',
			cursor: 'pointer',
			position: 'relative',
			margin: '0',
			boxSizing: 'border-box',
			alignSelf: 'center',
			':hover': {
				background: 'transparent',
				backgroundColor: 'transparent',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':focus': {
				background: 'transparent',
				backgroundColor: 'transparent',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':active': {
				background: 'transparent',
				backgroundColor: 'transparent',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
		},
		Burger_line1: {
			position: 'absolute',
			left: 'calc(50% - 12px)',
			width: '24px',
			height: '2px',
			borderRadius: '2px',
			backgroundColor: '#fff313',
			transition: 'top 0.25s ease, transform 0.25s ease, opacity 0.25s ease',
			transformOrigin: '50% 50%',
			boxSizing: 'border-box',
			top: 'calc(50% - 8px)',
			transform: 'none',
		},
		Burger_line2: {
			position: 'absolute',
			left: 'calc(50% - 12px)',
			width: '24px',
			height: '2px',
			borderRadius: '2px',
			backgroundColor: '#fff313',
			transition: 'top 0.25s ease, transform 0.25s ease, opacity 0.25s ease',
			transformOrigin: '50% 50%',
			boxSizing: 'border-box',
			top: 'calc(50% - 1px)',
			transform: 'none',
			opacity: '1',
		},
		Burger_line3: {
			position: 'absolute',
			left: 'calc(50% - 12px)',
			width: '24px',
			height: '2px',
			borderRadius: '2px',
			backgroundColor: '#fff313',
			transition: 'top 0.25s ease, transform 0.25s ease, opacity 0.25s ease',
			transformOrigin: '50% 50%',
			boxSizing: 'border-box',
			top: 'calc(50% + 6px)',
			transform: 'none',
		},
		'@': {
			piterjs_landing_rsvp_open: {
				true: {
					overflowY: 'hidden',
				},
			},
			piterjs_landing_menu_open: {
				true: {
					Burger_line1: {
						top: 'calc(50% - 1px)',
						transform: 'rotate(45deg)',
					},
					Burger_line2: {
						top: 'calc(50% - 1px)',
						opacity: '0',
						transform: 'scaleX(0)',
					},
					Burger_line3: {
						top: 'calc(50% - 1px)',
						transform: 'rotate(-45deg)',
					},
				},
			},
		},
		Nav_mobile: {
			display: 'none',
		},
		Main: {
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
		},
		Section_hero: {
			position: 'relative',
			minHeight: '100vh',
			height: 'auto',
			display: 'flex',
			flexDirection: 'column',
			justifyContent: 'center',
			alignItems: 'center',
			padding: '130px 36px 96px 36px',
			backgroundColor: '#000000',
			backgroundImage: 'url(\'piterjs/landing/assets/hero_poster.webp\')',
			backgroundSize: 'cover',
			backgroundPosition: 'center',
			overflow: 'hidden',
			boxSizing: 'border-box',
		},
		Hero_video: {
			position: 'absolute',
			inset: '0',
			width: '100%',
			height: '100%',
			objectFit: 'cover',
			objectPosition: 'center',
			zIndex: '0',
			pointerEvents: 'none',
			border: '0',
		},
		Hero_scrim: {
			position: 'absolute',
			inset: '0',
			zIndex: '1',
			pointerEvents: 'none',
			backgroundImage: 'radial-gradient(circle at 80% 20%, rgba(255, 243, 19, 0.05) 0%, transparent 40%), 	                  linear-gradient(to bottom, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.95))',
		},
		Hero_content: {
			maxWidth: '1200px',
			width: '100%',
			position: 'relative',
			zIndex: '2',
			display: 'flex',
			flexDirection: 'column',
			gap: '24px',
			// растягиваем на всю высоту героя, иначе Hero_intro не к чему
			// растягивать и карточки не уезжают вниз
			flex: '1 1 auto',
		},
		// Заголовочная группа забирает всё свободное место и центрует себя
		// внутри него: текст стоит по центру, а Hero_footer_grid прижат к низу.
		Hero_intro: {
			display: 'flex',
			flexDirection: 'column',
			justifyContent: 'center',
			gap: '24px',
			flex: '1 1 auto',
			minHeight: '0',
		},
		Hero_status_row: {
			display: 'flex',
			alignItems: 'center',
			gap: '16px',
			flexWrap: 'wrap',
		},
		Status_badge: {
			display: 'inline-flex',
			alignItems: 'center',
			gap: '8px',
			background: '#111111',
			border: '1px solid #333333',
			padding: '6px 14px',
			borderRadius: '6px',
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			letterSpacing: '0.5px',
			color: 'var(--color-caution-yellow)',
		},
		Hero_title: {
			fontSize: '64px',
			lineHeight: '1.05',
			letterSpacing: '-2.56px',
			fontWeight: '300',
			color: '#eeeeee',
			maxWidth: '1200px',
			marginBottom: '8px',
			textTransform: 'uppercase',
			display: 'flex',
			flexDirection: 'column',
			gap: '4px',
		},
		Hero_title_line1: {
			display: 'block',
			color: '#eeeeee',
			fontWeight: '300',
		},
		Hero_title_line2: {
			display: 'flex',
			alignItems: 'baseline',
			gap: '16px',
		},
		Hero_title_accent: {
			color: '#fff313',
			fontWeight: '300',
			display: 'inline',
		},
		Hero_title_rest: {
			color: '#eeeeee',
			fontWeight: '300',
			display: 'inline',
		},
		Hero_subtitle: {
			fontSize: 'clamp(16px, 1.8vw, 20px)',
			color: '#cccccc',
			maxWidth: '1000px',
			lineHeight: '1.5',
			fontWeight: '300',
		},
		Hero_footer_grid: {
			display: 'grid',
			gridTemplateColumns: '1fr 480px',
			gap: '32px',
			alignItems: 'flex-end',
			marginTop: 'auto',
			width: '100%',
		},
		Countdown_box: {
			backgroundColor: 'rgba(45, 45, 45, 0.75)',
			border: '1px solid #4b4b4b',
			borderRadius: '12px',
			padding: '24px 32px',
			// высота как в состоянии с отсчётом: 24+24 padding + подпись 14 +
			// gap 16 + колонка Unit (38px цифра + 6 отступ + 10 подпись) ≈ 158px.
			// Замерено на живой странице; на мобильном сбрасывается в auto,
			// там цифры 26px и коробка ниже.
			minHeight: '158px',
			boxSizing: 'border-box',
			justifyContent: 'center',
			// точка отсчёта для cqw у Cfp_promo
			containerType: 'inline-size',
			backdropFilter: 'blur(10px)',
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
			boxShadow: '0 10px 30px rgba(0, 0, 0, 0.5)',
		},
		// Тот же шрифт, что у цифр отсчёта (Unit_val), но кегль подбирается под
		// ширину коробки, чтобы строка не переносилась. Считаем в cqw, а не в vw:
		// на 992px грид схлопывается в одну колонку и коробка резко расширяется,
		// так что привязка к ширине окна дала бы разрыв.
		//
		// Замерено через Range: 32 знака с трекингом -0.5px занимают 18.6em - 16px.
		// При 5cqw запас до края коробки не меньше 60px на всех брейкпоинтах от
		// 390 до 1440, включая 993px, где колонка самая узкая (345px внутри).
		Cfp_promo: {
			fontFamily: '\'JetBrains Mono\', monospace',
			fontSize: 'clamp(9px, calc((100cqi - 64px) / 20), 32px)',
			fontWeight: '400',
			color: '#fff313',
			lineHeight: '1.15',
			letterSpacing: '-0.5px',
			whiteSpace: 'nowrap',
			textTransform: 'uppercase',
		},
		Cfp_promo_btn: {
			... cfp_btn,
			alignSelf: 'flex-start',
		},
		Countdown_label: {
			fontFamily: '\'JetBrains Mono\', monospace',
			fontSize: '11px',
			color: '#afafaf',
			textTransform: 'uppercase',
			letterSpacing: '0.5px',
			display: 'block',
		},
		Timer_units: {
			display: 'flex',
			gap: '36px',
			alignItems: 'flex-start',
		},
		Unit: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'flex-start',
			background: 'transparent',
			border: 'none',
			padding: '0',
		},
		Unit_val: {
			fontFamily: '\'JetBrains Mono\', monospace',
			fontSize: '38px',
			fontWeight: '400',
			color: '#fff313',
			lineHeight: '1',
			marginBottom: '6px',
		},
		Unit_tag: {
			fontFamily: '\'Inter\', sans-serif',
			fontSize: '10px',
			color: '#afafaf',
			textTransform: 'uppercase',
			letterSpacing: '0.5px',
		},
		Countdown_skeleton: {
			display: 'flex',
			flexDirection: 'column',
			gap: '12px',
			width: '100%',
			boxSizing: 'border-box',
		},
		Countdown_skel_line1: {
			... skel_base,
			height: '14px',
			width: '55%',
		},
		Countdown_skel_line2: {
			... skel_base,
			height: '32px',
			width: '80%',
		},
		Countdown_skel_btn: {
			... skel_base,
			height: '32px',
			width: '140px',
			borderRadius: '6px',
			marginTop: '4px',
		},
		Discovery_card: {
			backgroundColor: '#2b2b2b',
			border: '1px solid #4b4b4b',
			borderRadius: '12px',
			padding: '26px 28px',
			display: 'flex',
			flexDirection: 'column',
			gap: '14px',
			position: 'relative',
			overflow: 'hidden',
			boxShadow: '0 20px 40px rgba(0, 0, 0, 0.6)',
		},
		Discovery_skeleton: {
			display: 'flex',
			flexDirection: 'column',
			gap: '14px',
			width: '100%',
			boxSizing: 'border-box',
		},
		Disc_skel_badge: {
			... skel_base,
			height: '14px',
			width: '90px',
		},
		Disc_skel_title1: {
			... skel_base,
			height: '20px',
			width: '90%',
		},
		Disc_skel_title2: {
			... skel_base,
			height: '20px',
			width: '65%',
		},
		Disc_skel_meta1: {
			... skel_base,
			height: '14px',
			width: '50%',
		},
		Disc_skel_meta2: {
			... skel_base,
			height: '14px',
			width: '40%',
		},
		Disc_badge: {
			fontFamily: '\'JetBrains Mono\', monospace',
			fontSize: '11px',
			color: '#fff313',
			textTransform: 'uppercase',
			letterSpacing: '0.5px',
			fontWeight: '600',
		},
		Disc_title: {
			fontSize: '19px',
			fontWeight: '500',
			color: '#ffffff',
			lineHeight: '1.4',
		},
		Disc_meta_time: {
			display: 'flex',
			alignItems: 'center',
			gap: '10px',
			fontSize: '13px',
			color: '#afafaf',
		},
		Disc_meta_place: {
			display: 'flex',
			alignItems: 'center',
			gap: '10px',
			fontSize: '13px',
			color: '#afafaf',
		},
		Disc_meta_map: {
			display: 'flex',
			alignItems: 'center',
			gap: '10px',
			fontSize: '13px',
			color: '#afafaf',
		},
		Map_link: pill_link,
		Review_link: pill_link,
		Section_manifesto: {
			backgroundColor: 'var(--color-caution-yellow)',
			color: '#000000',
			padding: '90px 32px',
			display: 'flex',
			justifyContent: 'center',
		},
		Manifesto_content: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '60px',
		},
		Manifesto_quote: {
			fontSize: 'clamp(24px, 3.8vw, 44px)',
			fontWeight: '400',
			lineHeight: '1.25',
			letterSpacing: '-0.03em',
			color: '#000000',
			maxWidth: '1050px',
		},
		Stats_grid: {
			display: 'grid',
			gridTemplateColumns: 'repeat(4, 1fr)',
			gap: '24px',
			borderTop: '2px solid rgba(0, 0, 0, 0.15)',
			paddingTop: '40px',
		},
		Stat: {
			display: 'flex',
			flexDirection: 'column',
			gap: '6px',
		},
		Stat_val: {
			fontFamily: 'var(--font-mono)',
			fontSize: 'clamp(32px, 4vw, 48px)',
			fontWeight: '700',
			color: '#000000',
			letterSpacing: '-1px',
			marginBottom: '6px',
		},
		Stat_lbl: {
			fontSize: '14px',
			fontWeight: '500',
			color: '#333333',
			lineHeight: '1.3',
		},
		Section_schedule: {
			backgroundColor: 'var(--color-industrial-white)',
			color: '#000000',
			padding: '90px 32px',
			display: 'flex',
			justifyContent: 'center',
		},
		Schedule_content: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '36px',
		},
		Schedule_heading: {
			fontSize: 'clamp(28px, 4vw, 44px)',
			fontWeight: '300',
			letterSpacing: '-0.04em',
			color: '#000000',
			textTransform: 'uppercase',
		},
		Schedule_intro: {
			fontSize: '18px',
			color: '#4b4b4b',
			maxWidth: '800px',
			lineHeight: '1.5',
			marginTop: '-16px',
		},
		Talks_grid: {
			display: 'grid',
			gridTemplateColumns: '1fr 1fr',
			gap: '24px',
		},
		Talk: {
			background: '#ffffff',
			border: '1px solid #dcdcdc',
			borderRadius: '9px',
			padding: '28px',
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
			transition: 'border-color 0.15s ease, background-color 0.15s ease',
			':hover': {
				borderColor: '#000000',
				backgroundColor: '#fcfcfc',
			},
		},
		Talk_top: {
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		Talk_tag: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			background: '#000000',
			color: 'var(--color-caution-yellow)',
			padding: '4px 10px',
			borderRadius: '4px',
		},
		Talk_time: {
			fontFamily: 'var(--font-mono)',
			fontSize: '13px',
			fontWeight: '600',
			color: '#666666',
		},
		Talk_title: {
			fontSize: '20px',
			fontWeight: '600',
			color: '#000000',
			lineHeight: '1.35',
		},
		Talk_abstract: {
			fontSize: '14px',
			color: '#555555',
			lineHeight: '1.5',
			// сам клип в 6 строк — в landing.view.css: -webkit-line-clamp
			// через $mol_style_define не выразить, см. комментарий там
		},
		Talk_more: {
			textTransform: 'uppercase',
			alignSelf: 'flex-start',
			background: 'transparent',
			border: 'none',
			boxShadow: 'none',
			padding: '0',
			marginTop: '-8px',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			cursor: 'pointer',
			textDecoration: 'underline',
			transition: 'color 0.15s ease',
			':hover': {
				background: 'transparent',
				boxShadow: 'none',
				color: '#666666',
			},
		},
		Talk_speaker: {
			display: 'flex',
			flexDirection: 'row',
			alignItems: 'flex-start',
			gap: '14px',
			marginTop: 'auto',
			paddingTop: '16px',
			borderTop: '1px solid #eeeeee',
		},
		Speaker_photo: {
			width: '52px',
			height: '52px',
			borderRadius: '50%',
			objectFit: 'cover',
			border: '2px solid var(--color-caution-yellow)',
			flexShrink: '0',
		},
		Speaker_info: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'flex-start',
			gap: '4px',
			flex: '1 1 auto',
			minWidth: '0',
		},
		Speaker_name: {
			fontWeight: '600',
			fontSize: '15px',
			color: '#000000',
			display: 'block',
			lineHeight: '1.3',
		},
		Speaker_role: {
			fontSize: '12px',
			color: '#666666',
			fontFamily: 'var(--font-mono)',
			display: 'block',
			whiteSpace: 'normal',
			wordBreak: 'break-word',
			lineHeight: '1.45',
			width: '100%',
		},
		Cfp_cta_card: {
			background: '#000000',
			color: '#ffffff',
			borderRadius: '9px',
			padding: '32px',
			display: 'flex',
			flexDirection: 'column',
			gap: '14px',
		},
		Cfp_cta_badge: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
			letterSpacing: '1px',
		},
		Cfp_cta_title: {
			fontSize: '22px',
			fontWeight: '400',
			letterSpacing: '-0.02em',
		},
		Cfp_cta_text: {
			fontSize: '15px',
			color: '#afafaf',
			lineHeight: '1.5',
			maxWidth: '800px',
		},
		Cfp_open_btn: {
			... cfp_btn,
			alignSelf: 'flex-start',
			marginTop: '8px',
		},
		Venue_card: {
			background: '#ffffff',
			border: '1px solid #dcdcdc',
			borderRadius: '9px',
			padding: '28px',
			display: 'flex',
			flexDirection: 'column',
			gap: '8px',
		},
		Venue_badge: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: '#777777',
		},
		Venue_title: {
			fontSize: '22px',
			fontWeight: '600',
			color: '#000000',
		},
		Venue_meta1: {
			fontSize: '14px',
			color: '#444444',
		},
		Venue_meta2: {
			fontSize: '14px',
			color: '#444444',
		},
		Venue_meta3: {
			fontSize: '14px',
			color: '#444444',
		},
		Venue_map_btn: {
			textTransform: 'uppercase',
			alignSelf: 'flex-start',
			display: 'inline-flex',
			width: 'auto',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontWeight: '600',
			fontSize: '13px',
			marginTop: '8px',
			textDecoration: 'underline',
			background: 'transparent',
			backgroundColor: 'transparent',
			padding: '0',
			':hover': {
				color: '#000000',
				background: 'transparent',
				backgroundColor: 'transparent',
				textDecoration: 'none',
			},
		},
		Section_archive: {
			backgroundColor: '#0b0d13',
			backgroundImage: 'radial-gradient(circle, rgba(255, 243, 19, 0.12) 1px, transparent 1px)',
			backgroundSize: '24px 24px',
			color: '#ffffff',
			borderTop: '1px solid #1f2430',
			padding: '90px 32px',
			display: 'flex',
			justifyContent: 'center',
			position: 'relative',
		},
		Archive_content: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '32px',
		},
		Archive_heading: {
			fontSize: 'clamp(28px, 4vw, 44px)',
			fontWeight: '300',
			letterSpacing: '-0.04em',
			textTransform: 'uppercase',
		},
		Archive_filters: {
			display: 'flex',
			gap: '8px',
			flexWrap: 'wrap',
			$mol_button_minor: {
				background: '#11141c',
				color: '#9aa2b4',
				border: '1px solid #242938',
				padding: '8px 20px',
				borderRadius: '6px',
				fontFamily: 'var(--font-mono)',
				fontSize: '13px',
				fontWeight: '500',
				cursor: 'pointer',
				transition: 'all 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
				':hover': {
					color: '#ffffff',
					borderColor: '#4a5368',
					background: '#181d28',
				},
				'@': {
					piterjs_landing_filter_active: {
						true: {
							background: 'var(--color-caution-yellow)',
							color: '#000000',
							borderColor: 'var(--color-caution-yellow)',
							fontWeight: '700',
							transform: 'translateY(-1px)',
							':hover': {
								background: 'var(--color-caution-yellow)',
								color: '#000000',
								borderColor: 'var(--color-caution-yellow)',
							},
						},
					},
				},
			},
		},
		Archive_grid: {
			display: 'grid',
			gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
			gap: '20px',
		},
		Archive_card: {
			background: 'rgba(14, 17, 24, 0.92)',
			backdropFilter: 'blur(8px)',
			border: '1px solid #202636',
			borderRadius: '9px',
			padding: '24px',
			display: 'flex',
			flexDirection: 'column',
			gap: '12px',
			transition: 'border-color 0.2s ease',
			':hover': {
				borderColor: 'var(--color-caution-yellow)',
			},
		},
		Card_event_tag: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
		},
		Card_title: {
			fontSize: '16px',
			fontWeight: '500',
			color: '#ffffff',
			lineHeight: '1.4',
		},
		Card_meta: {
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: '#838a9c',
			marginTop: 'auto',
			paddingTop: '12px',
			borderTop: '1px solid #1c2130',
		},
		Archive_more_box: {
			display: 'flex',
			justifyContent: 'center',
			alignItems: 'center',
			paddingTop: '16px',
			width: '100%',
		},
		Archive_more_btn: {
			textTransform: 'uppercase',
			background: '#11141c',
			border: '1px solid #242938',
			color: 'var(--color-caution-yellow)',
			fontFamily: 'var(--font-mono)',
			fontSize: '13px',
			fontWeight: '700',
			padding: '12px 36px',
			borderRadius: '6px',
			letterSpacing: '0.5px',
			cursor: 'pointer',
			transition: 'all 0.2s ease',
			boxShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
			':hover': {
				background: 'var(--color-caution-yellow)',
				color: '#000000',
				borderColor: 'var(--color-caution-yellow)',
				// без свечения: тень остаётся базовой, чтобы не было вспышки на transition
				boxShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
				transform: 'translateY(-1px)',
			},
		},
		Section_community: {
			backgroundColor: '#161616',
			color: '#ffffff',
			borderTop: '1px solid #282828',
			padding: '90px 32px',
			display: 'flex',
			justifyContent: 'center',
		},
		Community_content: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '32px',
		},
		Community_heading: {
			fontSize: 'clamp(28px, 4vw, 44px)',
			fontWeight: '300',
			letterSpacing: '-0.04em',
			textTransform: 'uppercase',
		},
		Community_cards: {
			display: 'grid',
			gridTemplateColumns: '1fr 1fr',
			gap: '24px',
		},
		Comm: {
			background: '#0d0d0d',
			border: '1px solid #2e2e2e',
			borderRadius: '9px',
			padding: '32px',
			display: 'flex',
			flexDirection: 'column',
			gap: '14px',
			height: '100%',
			boxSizing: 'border-box',
		},
		Comm_badge: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
			letterSpacing: '1px',
		},
		Comm_title: {
			fontSize: '22px',
			fontWeight: '600',
			color: '#ffffff',
		},
		Comm_text: {
			fontSize: '14px',
			color: '#aaaaaa',
			lineHeight: '1.5',
			marginBottom: '14px',
		},
		Comm_btn: {
			textTransform: 'uppercase',
			alignSelf: 'flex-start',
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: 'var(--color-caution-yellow)',
			textDecoration: 'none',
			padding: '8px 14px',
			border: '1px solid var(--color-caution-yellow)',
			borderRadius: '6px',
			marginTop: 'auto',
			transition: 'background-color 0.2s ease, color 0.2s ease',
			display: 'inline-flex',
			alignItems: 'center',
			cursor: 'pointer',
			':hover': {
				backgroundColor: 'var(--color-caution-yellow)',
				color: '#000000',
			},
		},
		Footer: {
			backgroundColor: '#000000',
			borderTop: '1px solid #222222',
			padding: '32px 36px',
			display: 'flex',
			justifyContent: 'center',
			alignItems: 'center',
			boxSizing: 'border-box',
		},
		Footer_inner: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
		},
		Footer_content: {
			width: '100%',
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
			flexWrap: 'wrap',
			gap: '20px',
		},
		Footer_copy: {
			display: 'flex',
			alignItems: 'center',
			gap: '12px',
		},
		Footer_logo: {
			width: '24px',
			height: '24px',
			borderRadius: '4px',
		},
		Footer_text: {
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: '#777777',
		},
		Footer_bottom: {
			display: 'flex',
			alignItems: 'center',
			gap: '6px',
			paddingTop: '0',
			borderTop: 'none',
		},
		Footer_author_prefix: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			color: '#555555',
			letterSpacing: '0.5px',
		},
		Footer_author: {
			background: 'transparent',
			backgroundColor: 'transparent',
			padding: '0',
			margin: '0',
			border: 'none',
			boxShadow: 'none',
			outline: 'none',
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			color: '#777777',
			textDecoration: 'none',
			textTransform: 'uppercase',
			letterSpacing: '0.5px',
			transition: 'color 0.15s ease',
			display: 'inline-block',
			height: 'auto',
			minHeight: '0',
			lineHeight: '1',
			':hover': {
				background: 'transparent',
				backgroundColor: 'transparent',
				color: 'var(--color-caution-yellow)',
				textDecoration: 'underline',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':focus': {
				background: 'transparent',
				backgroundColor: 'transparent',
				color: 'var(--color-caution-yellow)',
				textDecoration: 'underline',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':active': {
				background: 'transparent',
				backgroundColor: 'transparent',
				color: 'var(--color-caution-yellow)',
				textDecoration: 'underline',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
		},
		Footer_links: {
			display: 'flex',
			alignItems: 'center',
			gap: '16px',
		},
		Soc: {
			background: 'transparent',
			backgroundColor: 'transparent',
			padding: '0',
			margin: '0',
			border: 'none',
			boxShadow: 'none',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			opacity: '0.6',
			transition: 'opacity 0.15s ease',
			cursor: 'pointer',
			':hover': {
				background: 'transparent',
				backgroundColor: 'transparent',
				opacity: '1',
			},
		},
		Soc_icon: {
			width: '22px',
			height: '22px',
			objectFit: 'contain',
			display: 'block',
			background: 'transparent',
			backgroundColor: 'transparent',
		},
		Cfp_modal: {
			position: 'fixed',
			top: '0',
			left: '0',
			width: '100vw',
			height: '100vh',
			background: 'rgba(0, 0, 0, 0.85)',
			backdropFilter: 'blur(8px)',
			zIndex: '1000',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			padding: '20px',
		},
		Cfp_modal_box: {
			background: '#111111',
			border: '1px solid #333333',
			borderRadius: '9px',
			maxWidth: '580px',
			width: '100%',
			maxHeight: '90vh',
			overflowY: 'auto',
			padding: '32px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			boxShadow: '0 20px 60px rgba(0, 0, 0, 0.8)',
		},
		Cfp_header: {
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		Cfp_header_title: {
			fontFamily: 'var(--font-mono)',
			fontSize: '16px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
		},
		Cfp_close_btn: close_btn,
		Cfp_desc: {
			fontSize: '14px',
			color: '#aaaaaa',
			lineHeight: '1.4',
		},
		Cfp_form: {
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
			width: '100%',
			$mol_textarea: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				minHeight: '120px',
				width: '100%',
				boxSizing: 'border-box',
				fontFamily: 'inherit',
				fontSize: '14px',
				lineHeight: '1.5',
				padding: '0',
				position: 'relative',
				overflow: 'hidden',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
			$mol_textarea_edit: {
				position: 'absolute',
				top: '0',
				left: '0',
				width: '100%',
				height: '100%',
				background: 'transparent',
				border: 'none',
				color: 'transparent',
				caretColor: '#fff313',
				padding: '10px 14px',
				margin: '0',
				fontFamily: 'inherit',
				fontSize: '14px',
				lineHeight: '1.5',
				boxSizing: 'border-box',
				boxShadow: 'none',
				outline: 'none',
				zIndex: '2',
			},
			$mol_textarea_view: {
				background: 'transparent',
				padding: '0',
				margin: '0',
				fontFamily: 'inherit',
				fontSize: '14px',
				lineHeight: '1.5',
				minHeight: '120px',
				width: '100%',
				boxSizing: 'border-box',
				zIndex: '1',
				display: 'block',
				$mol_text_code_rows: {
					padding: '10px 14px',
					margin: '0',
					fontFamily: 'inherit',
					fontSize: '14px',
					lineHeight: '1.5',
					color: '#ffffff',
					boxSizing: 'border-box',
				},
				$mol_button_copy: {
					display: 'none',
				},
			},
		},
		Cfp_field_email: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_contact: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_name: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_company: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_title: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_desc: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
		},
		Cfp_label_email: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_contact: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_name: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_company: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_title: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_desc: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_submit_btn: {
			textTransform: 'uppercase',
			background: 'var(--color-caution-yellow)',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontWeight: '700',
			fontSize: '13px',
			padding: '12px',
			borderRadius: '6px',
			border: 'none',
			cursor: 'pointer',
			marginTop: '10px',
			width: '100%',
			justifyContent: 'center',
		},
		Toast: {
			position: 'fixed',
			bottom: '32px',
			right: '32px',
			background: '#000000',
			color: 'var(--color-caution-yellow)',
			border: '1px solid var(--color-caution-yellow)',
			borderRadius: '6px',
			padding: '14px 20px',
			fontFamily: 'var(--font-mono)',
			fontSize: '13px',
			boxShadow: '0 10px 30px rgba(0, 0, 0, 0.7)',
			zIndex: '2000',
			animation: 'pjs_slidein 0.3s ease',
		},
		Rsvp_modal: {
			position: 'fixed',
			top: '0',
			left: '0',
			width: '100%',
			height: '100%',
			zIndex: '3000',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			padding: '24px',
			boxSizing: 'border-box',
		},
		Rsvp_backdrop: {
			position: 'absolute',
			top: '0',
			left: '0',
			width: '100%',
			height: '100%',
			background: 'rgba(0, 0, 0, 0.82)',
			backdropFilter: 'blur(8px)',
			cursor: 'pointer',
			animation: 'pjs_backdrop_in 0.2s ease',
		},
		Rsvp_dialog: {
			position: 'relative',
			zIndex: '1',
			width: '100%',
			maxWidth: '520px',
			maxHeight: '100%',
			overflowY: 'auto',
			background: '#0d0d0d',
			border: '1px solid #2e2e2e',
			borderRadius: '12px',
			padding: '32px',
			display: 'flex',
			flexDirection: 'column',
			gap: '18px',
			boxSizing: 'border-box',
			boxShadow: '0 24px 60px rgba(0, 0, 0, 0.85)',
			animation: 'pjs_modal_in 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
		},
		Rsvp_head: {
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
			gap: '16px',
		},
		Rsvp_badge: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
			letterSpacing: '1px',
		},
		Rsvp_close_btn: close_btn,
		Rsvp_title: {
			fontSize: 'clamp(22px, 3vw, 30px)',
			fontWeight: '300',
			letterSpacing: '-0.03em',
			textTransform: 'uppercase',
			color: '#ffffff',
			lineHeight: '1.15',
		},
		Rsvp_meta: {
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: '#aaaaaa',
			letterSpacing: '0.5px',
		},
		Rsvp_note: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			color: 'var(--color-caution-yellow)',
			letterSpacing: '1px',
			textTransform: 'uppercase',
		},
		Next_event_reg: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '10px',
			paddingTop: '4px',
			borderTop: '1px solid #202020',
		},
		Next_event_reg_label: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: 'var(--color-aluminum)',
			letterSpacing: '1px',
			textTransform: 'uppercase',
			paddingTop: '10px',
		},
		Next_event_reg_input: {
			background: '#1a1a1a',
			border: '1px solid #333333',
			borderRadius: '6px',
			color: '#ffffff',
			padding: '12px 14px',
			fontSize: '15px',
			width: '100%',
			boxSizing: 'border-box',
			transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
			// $mol_string ставит себе inset-рамки через box-shadow — гасим, у нас свой border
			boxShadow: 'none',
			':hover': {
				boxShadow: 'none',
			},
			':focus': {
				borderColor: 'var(--color-caution-yellow)',
				boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				outline: 'none',
			},
			'::placeholder': {
				color: '#5a5a5a',
			},
		},
		Next_event_reg_check: {
			textTransform: 'uppercase',
			alignSelf: 'flex-start',
			background: '#11141c',
			color: '#9aa2b4',
			border: '1px solid #242938',
			borderRadius: '6px',
			padding: '10px 18px',
			marginTop: '6px',
			fontFamily: 'var(--font-mono)',
			fontSize: '13px',
			cursor: 'pointer',
			transition: 'all 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
			':hover': {
				color: '#ffffff',
				borderColor: '#4a5368',
				background: '#181d28',
			},
			'@': {
				mol_check_checked: {
					true: {
						background: 'var(--color-caution-yellow)',
						color: '#000000',
						borderColor: 'var(--color-caution-yellow)',
						fontWeight: '700',
						':hover': {
							background: 'var(--color-caution-yellow)',
							color: '#000000',
							borderColor: 'var(--color-caution-yellow)',
						},
					},
				},
			},
		},
		'@media': {
			'(max-width: 1200px)': {
				Back_link: {
					display: 'none',
				},
			},
			'(max-width: 992px)': {
				Burger_btn: {
					display: 'flex',
				},
				Nav: {
					display: 'none',
				},
				Header: {
					position: 'fixed',
					top: '0',
					left: '0',
					width: '100%',
					zIndex: '1000',
					backgroundColor: 'rgba(0, 0, 0, 0.95)',
					backdropFilter: 'blur(12px)',
				},
				Nav_mobile: {
					display: 'flex',
					position: 'fixed',
					top: '60px',
					left: '0',
					width: '100%',
					backgroundColor: '#161616',
					borderBottom: '1px solid #4b4b4b',
					flexDirection: 'column',
					padding: '20px',
					gap: '12px',
					borderRadius: '0 0 16px 16px',
					transform: 'translateY(-110%)',
					opacity: '0',
					pointerEvents: 'none',
					transition: 'transform 0.35s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.25s ease',
					boxShadow: '0 16px 32px rgba(0, 0, 0, 0.8)',
					zIndex: '900',
					$mol_link: {
						textAlign: 'center',
						padding: '12px',
						fontSize: '16px',
						color: '#eeeeee',
						textDecoration: 'none',
						borderRadius: '8px',
						background: '#111111',
						border: '1px solid #2a2a2a',
						':hover': {
							color: '#fff313',
							background: '#222222',
						},
					},
				},
				'@': {
					piterjs_landing_menu_open: {
						true: {
							Nav_mobile: {
								transform: 'translateY(0)',
								opacity: '1',
								pointerEvents: 'auto',
							},
						},
					},
				},
				Hero_title: {
					fontSize: '44px',
					letterSpacing: '-1.5px',
				},
				Manifesto_quote: {
					fontSize: '32px',
					lineHeight: '1.25',
				},
				Hero_footer_grid: {
					gridTemplateColumns: '1fr',
					gap: '24px',
				},
				Discovery_card: {
					order: '1',
				},
				Countdown_box: {
					order: '2',
				},
				Stats_grid: {
					gridTemplateColumns: '1fr 1fr',
					gap: '24px',
				},
				Talks_grid: {
					gridTemplateColumns: '1fr',
				},
				Archive_grid: {
					gridTemplateColumns: '1fr 1fr',
				},
				Cfp_cta_card: {
					flexDirection: 'column',
					gap: '24px',
					textAlign: 'center',
					alignItems: 'center',
				},
				Cfp_open_btn: {
					alignSelf: 'center',
				},
				Community_cards: {
					gridTemplateColumns: '1fr',
				},
				Footer_inner: {
					flexDirection: 'column',
					gap: '16px',
					textAlign: 'center',
					justifyContent: 'center',
				},
				Footer_copy: {
					flexDirection: 'column',
					gap: '12px',
				},
			},
			'(max-width: 768px)': {
				Header: {
					padding: '12px 16px',
				},
				Nav_actions: {
					gap: '8px',
				},
				Rsvp_btn: {
					padding: '6px 12px',
					height: '32px',
					minHeight: '32px',
					maxHeight: '32px',
					fontSize: '12px',
					display: 'inline-flex',
					alignItems: 'center',
					justifyContent: 'center',
					lineHeight: '1',
				},
			},
			'(max-width: 600px)': {
				Rsvp_modal: {
					padding: '12px',
				},
				Rsvp_dialog: {
					padding: '24px 20px',
					gap: '14px',
				},
				Header: {
					padding: '10px 12px',
				},
				Back_link: {
					display: 'none',
				},
				Rsvp_btn: {
					padding: '6px 10px',
					height: '32px',
					minHeight: '32px',
					maxHeight: '32px',
					fontSize: '11px',
					display: 'inline-flex',
					alignItems: 'center',
					justifyContent: 'center',
					lineHeight: '1',
				},
				Section_hero: {
					padding: '90px 12px 72px 12px',
					height: 'auto',
					minHeight: '100vh',
				},
				Section_manifesto: {
					padding: '48px 12px',
				},
				Section_schedule: {
					padding: '48px 12px',
				},
				Section_archive: {
					padding: '48px 12px',
				},
				Section_community: {
					padding: '48px 12px',
				},
				Footer: {
					padding: '32px 12px',
				},
				Countdown_box: {
					padding: '20px 16px',
					minHeight: 'auto',
				},

				Venue_card: {
					padding: '20px 16px',
				},
				Archive_card: {
					padding: '20px 16px',
				},
				Cfp_cta_card: {
					padding: '24px 16px',
				},
				Hero_title: {
					fontSize: '30px',
					letterSpacing: '-1px',
				},
				Hero_title_line2: {
					flexWrap: 'wrap',
					gap: '8px',
				},
				Manifesto_quote: {
					fontSize: '22px',
					lineHeight: '1.3',
				},
				Stats_grid: {
					gridTemplateColumns: '1fr',
					gap: '20px',
				},
				Archive_grid: {
					gridTemplateColumns: '1fr',
					gap: '16px',
				},
				Talks_grid: {
					gap: '20px',
				},
				Community_cards: {
					gap: '20px',
				},
				Timer_units: {
					display: 'flex',
					flexDirection: 'row',
					gap: '14px',
					flexWrap: 'nowrap',
					justifyContent: 'flex-start',
					alignItems: 'flex-start',
				},
				Unit_val: {
					fontSize: '26px',
				},
				Archive_filters: {
					flexWrap: 'wrap',
					gap: '8px',
				},
				Toast: {
					left: '12px',
					right: '12px',
					bottom: '12px',
					textAlign: 'center',
				},
			},
			'(max-width: 480px)': {
				Rsvp_btn: {
					display: 'none',
				},
				Hero_title: {
					fontSize: '26px',
				},
				Manifesto_quote: {
					fontSize: '20px',
				},
				Section_hero: {
					padding: '80px 10px 64px 10px',
				},
				Section_manifesto: {
					padding: '40px 10px',
				},
				Section_schedule: {
					padding: '40px 10px',
				},
				Section_archive: {
					padding: '40px 10px',
				},
				Section_community: {
					padding: '40px 10px',
				},
				Footer: {
					padding: '24px 10px',
				},
			},
		},
	} )

}
