name: Deploy

on:
  workflow_dispatch:
  push:
  pull_request:
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build app
      uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'piterjs'
        modules: 'app'
    
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'piterjs/app/-'
